name: Ci

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v3
        if: github.event_name != 'workflow_dispatch'  
        # 仅在 GitHub 环境中运行，跳过本地 act 运行时的鉴权问题，需要在后续版本修复。
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .
        # 注意：在本地运行 act 时，由于无法访问 GITHUB_TOKEN，会导致鉴权错误。
        # 将来可能需要更新鉴权模式，例如使用环境变量或其他方式模拟令牌。
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: auto format code"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    permissions:
      contents: write
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: project-enter.nvim
          treesitter: true
      - name: Pull latest changes
        run: git pull origin main
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(doc): auto generate docs"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
