name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['stable']

    steps:
      - uses: actions/checkout@v4
    # This Part seems never used.
    #   - name: Download stylua
    #     shell: bash
    #     run: |
    #       wget "https://github.com/JohnnyMorganz/StyLua/releases/download/v0.18.0/stylua-linux.zip" -P /home/runner/.local/bin
    #       unzip /home/runner/.local/bin/stylua-linux.zip -d /home/runner/.local/bin
    #       chmod +x /home/runner/.local/bin/stylua
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      - name: Install Busted
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 lua-busted
      - name: Run tests with Busted
        shell: bash
        run: |
          busted test
